language: node_js

node_js:
  - "4"
  - "5"

branches:
  except:
    - gh-pages

after_script:
  - if [[ `node --version` == *v5* ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi